name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: xKurty06
          outputs: |
            dist/snake.svg
          color_snake: "#00FFFF" # Aqua
          color_dots: "#000000 #111111 #1a1a1a #222222 #333333" # Black to dark gray gradient background

      - name: Upload Snake
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
