name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *" # Runs every 12 hours
  workflow_dispatch:      # Allows manual run
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate GitHub Contribution Snake
        uses: Platane/snk@v3
        with:
          github_user_name: xKurty06
          outputs: dist/snake.svg
          color_snake: "#05cbf7" # Neon blue snake
          color_dots: "#0a0a0a #1a1a1a #222222 #444444 #05cbf7" # Dark background with blue accents

      - name: Push the generated snake file
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
